use_frameworks!

platform :ios, '10.0'

target 'RyCyxbsExtensionOC_Example' do
  pod 'RyCyxbsExtensionOC', :path => '../'

  target 'RyCyxbsExtensionOC_Tests' do
    inherit! :search_paths

    
  end
end
